# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('def_user', '0002_auto_20180316_2030'),
        ('def_goods', '0002_auto_20180313_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_count', models.IntegerField(max_length=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_goods.GoodsInfo')),
            ],
            options={
                'db_table': 'OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_number', models.CharField(max_length=20)),
                ('pay_or_not', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('total_count', models.IntegerField(default=0, max_length=6)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_user.UserInfo')),
            ],
            options={
                'db_table': 'OrderInfo',
            },
        ),
        migrations.CreateModel(
            name='PayWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'PayWay',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pay_way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_order.PayWay'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_order.OrderInfo'),
        ),
    ]
