# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='water_number',
            field=models.IntegerField(),
        ),
    ]
