# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gjianjie',
            new_name='gjianjie',
        ),
    ]
